package com.ashutosh.mindfultennis.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL
import com.ashutosh.mindfultennis.data.local.db.dao.FocusPointDao
import com.ashutosh.mindfultennis.data.local.db.dao.OpponentDao
import com.ashutosh.mindfultennis.data.local.db.dao.PartnerDao
import com.ashutosh.mindfultennis.data.local.db.dao.PartnerRatingDao
import com.ashutosh.mindfultennis.data.local.db.dao.SelfRatingDao
import com.ashutosh.mindfultennis.data.local.db.dao.SessionDao
import com.ashutosh.mindfultennis.data.local.db.dao.SetScoreDao
import com.ashutosh.mindfultennis.data.local.db.entity.FocusPointEntity
import com.ashutosh.mindfultennis.data.local.db.entity.OpponentEntity
import com.ashutosh.mindfultennis.data.local.db.entity.PartnerEntity
import com.ashutosh.mindfultennis.data.local.db.entity.PartnerRatingEntity
import com.ashutosh.mindfultennis.data.local.db.entity.SelfRatingEntity
import com.ashutosh.mindfultennis.data.local.db.entity.SessionEntity
import com.ashutosh.mindfultennis.data.local.db.entity.SetScoreEntity

@Database(
    entities = [
        SessionEntity::class,
        SelfRatingEntity::class,
        PartnerRatingEntity::class,
        FocusPointEntity::class,
        OpponentEntity::class,
        PartnerEntity::class,
        SetScoreEntity::class,
    ],
    version = 3,
    exportSchema = false,
)
@ConstructedBy(MindfulDatabaseConstructor::class)
abstract class MindfulDatabase : RoomDatabase() {

    abstract fun sessionDao(): SessionDao
    abstract fun selfRatingDao(): SelfRatingDao
    abstract fun partnerRatingDao(): PartnerRatingDao
    abstract fun focusPointDao(): FocusPointDao
    abstract fun opponentDao(): OpponentDao
    abstract fun partnerDao(): PartnerDao
    abstract fun setScoreDao(): SetScoreDao

    companion object {
        const val DATABASE_NAME = "mindful_sports_db"

        /**
         * v2 → v3: Add sport_id discriminator column to all sport-scoped tables.
         * Existing rows default to 'tennis' — the only sport that existed before v3.
         */
        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(connection: SQLiteConnection) {
                connection.execSQL("ALTER TABLE sessions ADD COLUMN sport_id TEXT NOT NULL DEFAULT 'tennis'")
                connection.execSQL("ALTER TABLE focus_points ADD COLUMN sport_id TEXT NOT NULL DEFAULT 'tennis'")
                connection.execSQL("ALTER TABLE opponents ADD COLUMN sport_id TEXT NOT NULL DEFAULT 'tennis'")
                connection.execSQL("ALTER TABLE partners ADD COLUMN sport_id TEXT NOT NULL DEFAULT 'tennis'")
            }
        }
    }
}

// Room KMP requires this — implementation is generated by the Room compiler
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object MindfulDatabaseConstructor : RoomDatabaseConstructor<MindfulDatabase> {
    override fun initialize(): MindfulDatabase
}
